### PR TITLE
hcce codes and dockerfiles

### PR DESCRIPTION
**Pull request by tanfarming**
+ codes and/or docker files that can be used to recreate all services/dependencies of hubs cloud community edition

### CODE REVIEW

**Comment by mikemorran** [comment]
@tanfarming just finished testing out and I have a couple of other notes....

A. I got this error with line 19 of `dockerbuildall.sh`: "dockerbuildall.sh: line 19: ${dir,,}: bad substitution"
B. Hubs' npm ci fails with a known error with PhantomJS (see this thread: https://discord.com/channels/498741086295031808/1182025615201804338/1196738177357066240). It can be fixed by specifying --platform=linux/amd64 but I wanted to ask your official take on the best way to fix it.

**Comment by tanfarming** [comment]
> A. I got this error with line 19 of `dockerbuildall.sh`: "dockerbuildall.sh: line 19: ${dir,,}: bad substitution" 

yeah i tested it on bash4, i guess you are running bash3? try to replace it with `tag_name="${tagPrefix}$(echo "$dir" | tr '[:upper:]' '[:lower:]')"` or `tag_name="${tagPrefix}$(echo "$dir" | awk '{print tolower($0)}')"` (cred. chatgpt lol)

> B. Hubs' npm ci fails with a known error with PhantomJS (see this thread: https://discord.com/channels/498741086295031808/1182025615201804338/1196738177357066240). It can be fixed by specifying --platform=linux/amd64 but I wanted to ask your official take on the best way to fix it.

yep HrithikWins' answer there is perfect, tldr -- add `--platform=linux/amd64` for none amd64 envs

**Comment by mikemorran** [comment]
Cool! I may just add a mention for it in the readme before deploying!

**Review by mikemorran — APPROVED** [review]
All good on my end!

**Pull request merged**
